name: Send Daily Tenders (Email→Telegram)

on:
  schedule:
    - cron: '0 * * * *'   # هر ساعت (UTC)؛ داخل اسکریپت می‌توانی گارد ۹ صبح پاریس داشته باشی
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    # ⬇️ سکرت‌ها را یک‌بار در سطح job ست می‌کنیم تا همه‌ی steps ببینند
    env:
      IMAP_HOST: ${{ secrets.IMAP_HOST || vars.IMAP_HOST }}
      IMAP_USER: ${{ secrets.IMAP_USER || vars.IMAP_USER }}
      IMAP_PASS: ${{ secrets.IMAP_PASS || vars.IMAP_PASS }}
      BOT_TOKEN:  ${{ secrets.BOT_TOKEN  || vars.BOT_TOKEN  }}
      GROUP_ID:   ${{ secrets.GROUP_ID   || vars.GROUP_ID   }}
      IMAP_FROM:  ${{ secrets.IMAP_FROM  || vars.IMAP_FROM  }}
      IMAP_SUBJECT_KEY: DAILY_TENDERS_JSON

    steps:
      - uses: actions/checkout@v4

      - name: Show repo tree
        run: |
          pwd
          ls -la

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Preflight env check
        run: |
          echo "Checking required envs..."
          miss=0
          for name in IMAP_HOST IMAP_USER IMAP_PASS BOT_TOKEN GROUP_ID IMAP_SUBJECT_KEY; do
            if [ -z "${!name}" ]; then
              echo "❌ MISSING: $name"; miss=1
            else
              echo "✅ $name is set"
            fi
          done
          test "$miss" -eq 0

      - name: Run
        run: python pull_and_send_from_email.py
