# .github/workflows/send-tenders.yml
name: Send Daily Tenders

on:
  schedule:
    - cron: '0 * * * *'   # هر ساعت (UTC)؛ داخل کد اگر گارد 9 صبح داری، فقط همان موقع ارسال می‌شود
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show repo tree (debug)
        run: |
          pwd
          ls -la

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run
        run: python send_tenders.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GROUP_ID: ${{ secrets.GROUP_ID }}
          # اگر این اسکریپت به ایمیل/IMAP نیاز ندارد، چیزی اضافه نکن
