name: Send Daily Tenders (Email→Telegram)

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show repo tree
        run: |
          pwd
          ls -la

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Preflight env check
        run: |
          echo "Checking required envs..."
          missing=0
          for name in IMAP_HOST IMAP_USER IMAP_PASS BOT_TOKEN GROUP_ID IMAP_SUBJECT_KEY; do
            if [ -z "${!name}" ]; then
              echo "❌ MISSING: $name"
              missing=1
            else
              echo "✅ $name is set"
            fi
          done
          if [ "$missing" -ne 0 ]; then
            echo "One or more envs are missing. Fix secrets/variables names."
            exit 1
          fi
        env:
          IMAP_HOST: ${{ secrets.IMAP_HOST }}
          IMAP_USER: ${{ secrets.IMAP_USER }}
          IMAP_PASS: ${{ secrets.IMAP_PASS }}   # ← اگر با vars ذخیره کرده‌ای، این را به vars.IMAP_PASS تغییر بده
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GROUP_ID: ${{ secrets.GROUP_ID }}
          IMAP_SUBJECT_KEY: DAILY_TENDERS_JSON

      - name: Run
        run: python pull_and_send_from_email.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GROUP_ID: ${{ secrets.GROUP_ID }}
          IMAP_USER: ${{ secrets.IMAP_USER }}
          IMAP_PASS: ${{ secrets.IMAP_PASS }}
          IMAP_HOST: ${{ secrets.IMAP_HOST }}
          IMAP_FROM: ${{ secrets.IMAP_FROM }}
          IMAP_SUBJECT_KEY: DAILY_TENDERS_JSON
