name: Send Daily Tenders (Email→Telegram)

on:
  schedule:
    - cron: '0 * * * *'   # هر ساعت (UTC)؛ اسکریپت فقط 09:00 پاریس ارسال می‌کند
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      IMAP_HOST: ${{ secrets.IMAP_HOST }}
      IMAP_USER: ${{ secrets.IMAP_USER }}
      IMAP_PASS: ${{ secrets.IMAP_PASS }}
      BOT_TOKEN:  ${{ secrets.BOT_TOKEN }}
      GROUP_ID:   ${{ secrets.GROUP_ID }}
      IMAP_FROM:  ${{ secrets.IMAP_FROM }}
      IMAP_SUBJECT_KEY: DAILY_TENDERS_JSON
      SEND_ERRORS_TO_CHAT: "1"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # اختیاری: تست ورود POP برای اطمینان
      - name: Test POP login
        run: |
          python - <<'PY'
          import os, poplib
          host=os.environ['IMAP_HOST']; user=os.environ['IMAP_USER']; pw=os.environ['IMAP_PASS']
          P=poplib.POP3_SSL(host,995,timeout=30); P.user(user); P.pass_(pw)
          c,_=P.stat(); print("✅ POP login OK, messages:", c); P.quit()
          PY

      - name: Run
        run: python pull_and_send_from_email.py
