name: Send Daily Tenders (Email→Telegram)

on:
  schedule:
    - cron: '0 * * * *'   # هر ساعت (UTC)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run
        run: python pull_and_send_from_email.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GROUP_ID: ${{ secrets.GROUP_ID }}
          IMAP_USER: ${{ secrets.IMAP_USER }}
          IMAP_PASS: ${{ secrets.IMAP_PASS }}
          IMAP_HOST: ${{ secrets.IMAP_HOST }}          # imap-mail.outlook.com یا imap.gmail.com
          IMAP_FROM: ${{ secrets.IMAP_FROM }}          # اختیاری
          IMAP_SUBJECT_KEY: DAILY_TENDERS_JSON
